services:
  traefik:
    command:
      - --log.level=WARN
    volumes:
      - traefik-certs:/etc/traefik/acme
    labels:
      - traefik.http.routers.dashboard.rule=Host(`traefik.yourdomain.com`)
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt

  database:
    env_file:
      - ./backend/.env.prod

  backend:
    image: ${REGISTRY:-rythmix}/backend:${TAG:-latest}
    build:
      target: prod
    env_file:
      - ./backend/.env.prod
    labels:
      - traefik.http.routers.backend.rule=Host(`api.yourdomain.com`)
      - traefik.http.routers.backend.tls.certresolver=letsencrypt

  back-office:
    image: ${REGISTRY:-rythmix}/back-office:${TAG:-latest}
    build:
      target: prod
    env_file:
      - ./back-office/.env.prod
    labels:
      - traefik.http.routers.backoffice.rule=Host(`admin.yourdomain.com`)
      - traefik.http.routers.backoffice.tls.certresolver=letsencrypt
      - traefik.http.services.backoffice.loadbalancer.server.port=80