services:
  traefik:
    command:
      - --log.level=INFO
    volumes:
      - ./traefik/certs:/etc/traefik/certs:ro
    labels:
      - traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)

  database:
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  backend:
    build:
      target: dev
    env_file:
      - ./backend/.env
    environment:
      - HOST=0.0.0.0
      - DB_HOST=database
    volumes:
      - ./backend:/app
      - /app/node_modules
    labels:
      - traefik.http.routers.backend.rule=Host(`api.localhost`)

  back-office:
    build:
      target: dev
    volumes:
      - ./back-office:/app
      - /app/node_modules
    env_file:
      - ./back-office/.env
    environment:
      - API_BASE_URL=http://backend:3333/api
    stdin_open: true
    tty: true
    labels:
      - traefik.http.routers.backoffice.rule=Host(`admin.localhost`)
      - traefik.http.services.backoffice.loadbalancer.server.port=4200
