name: Mobile CI

on:
  push:
    branches: [main, staging, MIX-194] # Added MIX-194 branch to trigger back-office CI for testing
    paths:
      - 'front-mobile/**'
      - '.github/workflows/ci-mobile.yml'
  pull_request:
    branches: [main, staging]
    paths:  
      - 'front-mobile/**'
      - '.github/workflows/ci-mobile.yml'

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front-mobile/package-lock.json'

      - name: Install dependencies
        run: npm ci
      - name: Run type checking
        run: npm run typecheck
      - name: Run linter
        run: npm run lint
      - name: Run code formatting check
        run: npm run format:check

  test:
    runs-on: ubuntu-latest
    # needs: quality
    defaults:
      run:
        working-directory: front-mobile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front-mobile/package-lock.json'
      - name: Install dependencies
        run: npm ci

      ##### setup test here if needed #####
      # - name: Run tests
      #   run: npm run test:coverage
